# https://aka.ms/vscode-remote/devcontainer/base
FROM mcr.microsoft.com/devcontainers/javascript-node:18

# Install any additional OS packages if needed
# RUN apt-get update && apt-get install -y <package-name>

# Set the working directory
WORKDIR /workspace

# Use the non-root 'node' user provided by the base image
USER node
